#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
	echo "Usage: ./download_images <input> <output_dir_name>";
	exit 1;
fi

if [ -f "$1" ]; then
	if [ ! -d "$2" ]; then
		mkdir $2;
	else
		rm -r $2;
	fi
	cat $1 | while read x; do wget -P $2 $x; done
else
	echo "Error: $1 does not exist";
	exit 1;
fi
